# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8029c60b85f959a6b8fe89ede077873f1e0c9e72ca1239453bedc54dd308fadeb86b89f50003c8dada809f7b2b5c74b6ebf155adf6d3209312cefca2bd2d8341

test:
  secret_key_base: ffcba714673f66ef9a35beeeecbcb709bdeeb3a700d0b0ea95fb830ddf89d9db6a3480077df7e70d5bdc035a4b8a952110044fff30d8cc34946e6d73d2b0e796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
